<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GedcomCommon\GedcomCommon.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="powershell -NonInteractive -ExecutionPolicy Unrestricted $(ProjectDir)..\scripts\copy_pre_commit.ps1 $(ProjectDir)..\scripts\pre-commit" />
  </Target>

</Project>
