# Copyright (c) Armidale Software
# SPDX-License-Identifier: MIT
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: MSBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  # Cancel any builds currently in progress for the same PR.
  # Allow running concurrently for with any other commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        configurations: [Debug, Release]
    runs-on: windows-2019
    env:
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: Gedcom7.sln

      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: ${{matrix.configurations}}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf  # v2.11.1
        with:
          egress-policy: audit

      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'false'
          paths_ignore: '["**.md"]'

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
        if: steps.skip_check.outputs.should_skip != 'true'
        with:
          submodules: 'recursive'

      - name: Add MSBuild to PATH
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: microsoft/setup-msbuild@v2

      - name: Set up VSTest Path
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: darenm/Setup-VSTest@v1

      - name: Restore NuGet packages
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ${{env.GITHUB_WORKSPACE}}
        # Add additional options to the MSBuild command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Analysis='True' ${{env.SOLUTION_FILE_PATH}}

      - name: Run Basic Unit Tests
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ./Tests/bin/${{env.BUILD_CONFIGURATION}}/net6.0
        run: vstest.console.exe Tests.dll /Logger:trx

      - name: Validate GEDCOM.io test files
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ${{github.workspace}}/GedValidate/bin/${{env.BUILD_CONFIGURATION}}/net6.0/
        run: |
          .\GedValidate.exe ${{github.workspace}}\external\GEDCOM-registries ${{github.workspace}}\external\GEDCOM-registries\registry_tools\GEDCOM.io\testfiles\gedcom70\

      - name: Dump memory usage
        if: steps.skip_check.outputs.should_skip != 'true'
        working-directory: ./Tests/bin/${{env.BUILD_CONFIGURATION}}/net6.0/TestResults
        run: findstr bytes *.trx

      - name: Upload GedValidate binary
        if: steps.skip_check.outputs.should_skip != 'true'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: Windows ${{env.BUILD_CONFIGURATION}} GedValidate
          path: ${{github.workspace}}/GedValidate/bin/${{env.BUILD_CONFIGURATION}}/net6.0/
          retention-days: 5
